/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "RooAbsPdf.h"                  // for RooAbsPdf
#include "RooExtendedBinding.h"         // for RooExtendedBinding, etc
#include "RooRealProxy.h"               // for RooRealProxy
#include "Rtypes.h"                     // for ClassImp, Double_t

ClassImp(RooExtendedBinding) 

 RooExtendedBinding::RooExtendedBinding(const char *name, const char *title, RooAbsPdf& _pdf) :
   RooAbsReal(name,title), 
   pdf("pdf","pdf",this,_pdf)
 { 
 } 


 RooExtendedBinding::RooExtendedBinding(const RooExtendedBinding& other, const char* name) :  
   RooAbsReal(other,name), 
   pdf("pdf",this,other.pdf)
 { 
 } 



 Double_t RooExtendedBinding::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   return ((RooAbsPdf&)pdf.arg()).expectedEvents(0) ; 
 } 



